SELECT 
        --BALANCE.CREATIONDATETIME,
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD-MM-YYYY HH:MI:SS') AS "CREATIONDATETIME",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'YYYY') AS "CYear",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'MM') AS "CMonth",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD') AS "CDay",
        BALANCE.CREATIONUSER,
        BALANCE.LOGICALWAREHOUSECODE,
        BALANCE.PROJECTCODE,
        BALANCE.ITEMTYPECODE,  
        TRIM(BALANCE.DECOSUBCODE01) AS "Articlecode",
        TRIM(BALANCE.DECOSUBCODE02) AS "Design",
        TRIM(BALANCE.DECOSUBCODE03) AS "Variant", -- set as text in excel
        TRIM(BALANCE.DECOSUBCODE04) AS "Color",
        TRIM(BALANCE.DECOSUBCODE05) AS "Marketing code",
        TRIM(BALANCE.DECOSUBCODE06) AS "Print /Design",
        TRIM(BALANCE.DECOSUBCODE07) AS "Full width",
        FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
        BALANCE.ELEMENTSCODE,                   -- set as text in excel
                        
        BALANCE.BASEPRIMARYQUANTITYUNIT,
        BALANCE.BASEPRIMARYUNITCODE,
        
        BALANCE.BASESECONDARYQUANTITYUNIT,
        BALANCE.BASESECONDARYUNITCODE,
        BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
        BALANCE.WAREHOUSELOCATIONCODE,
        BALANCE.QUALITYLEVELCODE,
        CASE BALANCE.STOCKTYPECODE
                WHEN '001' THEN 'Balance'
                WHEN '002' THEN 'Provisional Stock'
        END AS STOCKTYPE,
        BALANCE.LOTCODE
        
FROM DB2ADMIN.BALANCE BALANCE ,
        DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER
WHERE
        BALANCE.DECOSUBCODE01 = FULLITEMKEYDECODER.SUBCODE01
        AND BALANCE.DECOSUBCODE02 = FULLITEMKEYDECODER.SUBCODE02
        AND BALANCE.DECOSUBCODE03 = FULLITEMKEYDECODER.SUBCODE03
        AND BALANCE.DECOSUBCODE04 = FULLITEMKEYDECODER.SUBCODE04
        AND BALANCE.DECOSUBCODE05 = FULLITEMKEYDECODER.SUBCODE05
        AND BALANCE.DECOSUBCODE06 = FULLITEMKEYDECODER.SUBCODE06
        AND BALANCE.DECOSUBCODE07 = FULLITEMKEYDECODER.SUBCODE07
        AND BALANCE.LOGICALWAREHOUSECODE IN (:P_WAREHOUSE)      

ORDER BY BALANCE.CREATIONDATETIME;

