
-- Balance _Details

SELECT 
        --BALANCE.CREATIONDATETIME,
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD-MM-YYYY HH:MI:SS') AS "CREATIONDATETIME",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'YYYY') AS "CYEAR",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'MM') AS "CMONTH",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD') AS "CDAY",
        BALANCE.CREATIONUSER,
        BALANCE.LOGICALWAREHOUSECODE,
        BALANCE.PROJECTCODE,
        LEFT(BALANCE.PROJECTCODE, 10) AS "SALESORDER",
        BALANCE.ITEMTYPECODE,  
        TRIM(BALANCE.DECOSUBCODE01) AS "ARTICLECODE",
        TRIM(BALANCE.DECOSUBCODE02) AS "DESIGN",
        TRIM(BALANCE.DECOSUBCODE03) AS "VARIANT", -- set as text in excel
        TRIM(BALANCE.DECOSUBCODE04) AS "COLOR",
        TRIM(BALANCE.DECOSUBCODE05) AS "MARKETING CODE",
        TRIM(BALANCE.DECOSUBCODE06) AS "PRINT DESIGN",
        TRIM(BALANCE.DECOSUBCODE07) AS "FULL WIDTH",
        FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
        BALANCE.ELEMENTSCODE,                   -- set as text in excel
                        
        BALANCE.BASEPRIMARYQUANTITYUNIT,
        BALANCE.BASEPRIMARYUNITCODE,
        
        BALANCE.BASESECONDARYQUANTITYUNIT,
        BALANCE.BASESECONDARYUNITCODE,
        BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
        BALANCE.WAREHOUSELOCATIONCODE,
        BALANCE.QUALITYLEVELCODE,
        CASE BALANCE.STOCKTYPECODE
                WHEN '001' THEN 'Balance'
                WHEN '002' THEN 'Provisional Stock'
        END AS STOCKTYPE,
        BALANCE.LOTCODE,
        SALESORDER.CREATIONUSER AS "CREATIONSO",
        SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE AS "CUSTOMERCODE",
        BUSINESSPARTNER.LEGALNAME1 AS "CUSTOMER"
        
FROM DB2ADMIN.BALANCE BALANCE ,
     DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER,
     DB2ADMIN.SALESORDER SALESORDER,
     DB2ADMIN.ORDERPARTNER ORDERPARTNER ,
     DB2ADMIN.BUSINESSPARTNER BUSINESSPARTNER
WHERE
        BALANCE.DECOSUBCODE01 = FULLITEMKEYDECODER.SUBCODE01
        AND BALANCE.DECOSUBCODE02 = FULLITEMKEYDECODER.SUBCODE02
        AND BALANCE.DECOSUBCODE03 = FULLITEMKEYDECODER.SUBCODE03
        AND BALANCE.DECOSUBCODE04 = FULLITEMKEYDECODER.SUBCODE04
        AND BALANCE.DECOSUBCODE05 = FULLITEMKEYDECODER.SUBCODE05
        AND BALANCE.DECOSUBCODE06 = FULLITEMKEYDECODER.SUBCODE06
        AND BALANCE.DECOSUBCODE07 = FULLITEMKEYDECODER.SUBCODE07
        --AND BALANCE.LOGICALWAREHOUSECODE IN ('DP10FFB1')  
        
        -- MAPPING
        AND LEFT(BALANCE.PROJECTCODE, 10) = SALESORDER.CODE
        AND SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
        AND ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID

ORDER BY BALANCE.CREATIONDATETIME;
 
 --- SALESORDER MAPPING WITH PROJECT IN BALANCE
 
SELECT CODE, ORDPRNCUSTOMERSUPPLIERCODE, PROJECTCODE, CREATIONUSER, ABSUNIQUEID FROM SALESORDER
ORDER BY CREATIONDATETIME

-- ----------------------------------------------------------------------------------------------------
SELECT 
        ORDPRNCUSTOMERSUPPLIERCODE, CREATIONUSER 
FROM SALESORDER
ORDER BY CREATIONDATETIME     
 
SELECT PROJECTCODE,
        LEFT(PROJECTCODE, 10) AS "SALESORDER"
FROM BALANCE
ORDER BY PROJECTCODE

-- ORDERPARTNER WITH SALESORDER
 
SELECT CUSTOMERSUPPLIERCODE, ORDERBUSINESSPARTNERNUMBERID
FROM ORDERPARTNER
WHERE CUSTOMERSUPPLIERCODE = '102100'

-- BUSINESSPARTNER WITH ORDERPARTNER

SELECT NUMBERID, LEGALNAME1
FROM BUSINESSPARTNER
WHERE NUMBERID = '1154'


---------------------------------------------------------------------------------------------------------

SELECT 
        --BALANCE.CREATIONDATETIME,
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD-MM-YYYY HH:MI:SS') AS "CREATIONDATETIME",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'YYYY') AS "CYEAR",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'MM') AS "CMONTH",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD') AS "CDAY",
        BALANCE.CREATIONUSER,
        BALANCE.LOGICALWAREHOUSECODE,
        BALANCE.PROJECTCODE,
        LEFT(BALANCE.PROJECTCODE, 10) AS "SALESORDER",
        BALANCE.ITEMTYPECODE,  
        TRIM(BALANCE.DECOSUBCODE01) AS "ARTICLECODE",
        TRIM(BALANCE.DECOSUBCODE02) AS "DESIGN",
        TRIM(BALANCE.DECOSUBCODE03) AS "VARIANT", -- set as text in excel
        TRIM(BALANCE.DECOSUBCODE04) AS "COLOR",
        TRIM(BALANCE.DECOSUBCODE05) AS "MARKETING CODE",
        TRIM(BALANCE.DECOSUBCODE06) AS "PRINT DESIGN",
        TRIM(BALANCE.DECOSUBCODE07) AS "FULL WIDTH",
        FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
        BALANCE.ELEMENTSCODE,                   -- set as text in excel
                        
        BALANCE.BASEPRIMARYQUANTITYUNIT,
        BALANCE.BASEPRIMARYUNITCODE,
        
        BALANCE.BASESECONDARYQUANTITYUNIT,
        BALANCE.BASESECONDARYUNITCODE,
        BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
        BALANCE.WAREHOUSELOCATIONCODE,
        BALANCE.QUALITYLEVELCODE,
        CASE BALANCE.STOCKTYPECODE
                WHEN '001' THEN 'Balance'
                WHEN '002' THEN 'Provisional Stock'
        END AS STOCKTYPE,
        BALANCE.LOTCODE,
        UPPER(SALESORDER.CREATIONUSER)  AS "CSALESORDER" ,
        TRIM(SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE) AS "CUSTOMERCODE",
        BUSINESSPARTNER.LEGALNAME1 
        
FROM DB2ADMIN.BALANCE BALANCE
        LEFT JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON 
                BALANCE.DECOSUBCODE01 = FULLITEMKEYDECODER.SUBCODE01
                AND BALANCE.DECOSUBCODE02 = FULLITEMKEYDECODER.SUBCODE02
                AND BALANCE.DECOSUBCODE03 = FULLITEMKEYDECODER.SUBCODE03
                AND BALANCE.DECOSUBCODE04 = FULLITEMKEYDECODER.SUBCODE04
                AND BALANCE.DECOSUBCODE05 = FULLITEMKEYDECODER.SUBCODE05
                AND BALANCE.DECOSUBCODE06 = FULLITEMKEYDECODER.SUBCODE06
                AND BALANCE.DECOSUBCODE07 = FULLITEMKEYDECODER.SUBCODE07
        LEFT JOIN DB2ADMIN.SALESORDER SALESORDER ON 
                LEFT(BALANCE.PROJECTCODE, 10) = SALESORDER.CODE
        LEFT JOIN DB2ADMIN.ORDERPARTNER ORDERPARTNER ON 
                SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
                -- DUPLICATE CUSTOMERSUPPLIERCODE
                AND ORDERPARTNER.CUSTOMERSUPPLIERTYPE = '1'
        LEFT JOIN DB2ADMIN.BUSINESSPARTNER BUSINESSPARTNER ON 
                ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
WHERE BALANCE.LOGICALWAREHOUSECODE IN (:P_WAREHOUSE)
ORDER BY BALANCE.CREATIONDATETIME;



------------------------------------------------------------------
DROP VIEW VIEWDEVBALANCEDETAILS;
CREATE VIEW VIEWDEVBALANCEDETAILS AS

        SELECT 
                --BALANCE.CREATIONDATETIME,
                TO_CHAR(BALANCE.CREATIONDATETIME, 'DD-MM-YYYY HH:MI:SS') AS "CREATIONDATETIME",
                TO_CHAR(BALANCE.CREATIONDATETIME, 'YYYY') AS "CYEAR",
                TO_CHAR(BALANCE.CREATIONDATETIME, 'MM') AS "CMONTH",
                TO_CHAR(BALANCE.CREATIONDATETIME, 'DD') AS "CDAY",
                BALANCE.CREATIONUSER,
                BALANCE.LOGICALWAREHOUSECODE,
                BALANCE.PROJECTCODE,
                LEFT(BALANCE.PROJECTCODE, 10) AS "SALESORDER",
                BALANCE.ITEMTYPECODE,  
                TRIM(BALANCE.DECOSUBCODE01) AS "ARTICLECODE",
                TRIM(BALANCE.DECOSUBCODE02) AS "DESIGN",
                TRIM(BALANCE.DECOSUBCODE03) AS "VARIANT", -- set as text in excel
                TRIM(BALANCE.DECOSUBCODE04) AS "COLOR",
                TRIM(BALANCE.DECOSUBCODE05) AS "MARKETING CODE",
                TRIM(BALANCE.DECOSUBCODE06) AS "PRINT DESIGN",
                TRIM(BALANCE.DECOSUBCODE07) AS "FULL WIDTH",
                FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
                BALANCE.ELEMENTSCODE,                   -- set as text in excel
                                
                BALANCE.BASEPRIMARYQUANTITYUNIT,
                BALANCE.BASEPRIMARYUNITCODE,
                
                BALANCE.BASESECONDARYQUANTITYUNIT,
                BALANCE.BASESECONDARYUNITCODE,
                BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
                BALANCE.WAREHOUSELOCATIONCODE,
                BALANCE.QUALITYLEVELCODE,
                CASE BALANCE.STOCKTYPECODE
                        WHEN '001' THEN 'Balance'
                        WHEN '002' THEN 'Provisional Stock'
                END AS STOCKTYPE,
                BALANCE.LOTCODE,
                SALESORDER.CREATIONUSER AS "CREATIONSO",
                TRIM(SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE) AS "CUSTOMERCODE",
                TRIM(BUSINESSPARTNER.LEGALNAME1) AS "CUSTOMER",
                TRIM(ADSTORAGE.VALUESTRING) AS "SOLEADER"
                
        FROM DB2ADMIN.BALANCE BALANCE
                LEFT JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON 
                        BALANCE.DECOSUBCODE01 = FULLITEMKEYDECODER.SUBCODE01
                        AND BALANCE.DECOSUBCODE02 = FULLITEMKEYDECODER.SUBCODE02
                        AND BALANCE.DECOSUBCODE03 = FULLITEMKEYDECODER.SUBCODE03
                        AND BALANCE.DECOSUBCODE04 = FULLITEMKEYDECODER.SUBCODE04
                        AND BALANCE.DECOSUBCODE05 = FULLITEMKEYDECODER.SUBCODE05
                        AND BALANCE.DECOSUBCODE06 = FULLITEMKEYDECODER.SUBCODE06
                        AND BALANCE.DECOSUBCODE07 = FULLITEMKEYDECODER.SUBCODE07
                LEFT JOIN DB2ADMIN.SALESORDER SALESORDER ON 
                        LEFT(BALANCE.PROJECTCODE, 10) = SALESORDER.CODE
                LEFT JOIN DB2ADMIN.ORDERPARTNER ORDERPARTNER ON 
                        SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
                        -- DUPLICATE CUSTOMERSUPPLIERCODE
                        AND ORDERPARTNER.CUSTOMERSUPPLIERTYPE = '1'
                LEFT JOIN DB2ADMIN.BUSINESSPARTNER BUSINESSPARTNER ON 
                        ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
                LEFT JOIN (SELECT UNIQUEID, VALUESTRING 
                                FROM DB2ADMIN.ADSTORAGE
                                WHERE ADSTORAGE.NAMEENTITYNAME = 'SalesOrder' 
                                        AND  ADSTORAGE.NAMENAME = 'SalesLeader' ) ADSTORAGE ON
                        SALESORDER.ABSUNIQUEID = ADSTORAGE.UNIQUEID
        WHERE BALANCE.LOGICALWAREHOUSECODE IN (:P_WAREHOUSE)

        ORDER BY BALANCE.CREATIONDATETIME;

-- Gan quyen xem view
GRANT ALL ON VIEWBOOKANALYSIS TO PUBLIC;


----------------------------------------------------------------------------------------------------
-- Map Longdescription in UserGenericGroup about ActicleCode 

SELECT 
        --BALANCE.CREATIONDATETIME,
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD-MM-YYYY HH:MI:SS') AS "CREATIONDATETIME",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'YYYY') AS "CYEAR",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'MM') AS "CMONTH",
        TO_CHAR(BALANCE.CREATIONDATETIME, 'DD') AS "CDAY",
        BALANCE.CREATIONUSER,
        BALANCE.LOGICALWAREHOUSECODE,
        BALANCE.PROJECTCODE,
        LEFT(BALANCE.PROJECTCODE, 10) AS "SALESORDER",
        BALANCE.ITEMTYPECODE,  
        TRIM(BALANCE.DECOSUBCODE01) AS "ARTICLECODE",
        TRIM(BALANCE.DECOSUBCODE02) AS "DESIGN",
        TRIM(BALANCE.DECOSUBCODE03) AS "VARIANT", -- set as text in excel
        TRIM(BALANCE.DECOSUBCODE04) AS "COLOR",
        TRIM(BALANCE.DECOSUBCODE05) AS "MARKETING CODE",
        TRIM(BALANCE.DECOSUBCODE06) AS "PRINT DESIGN",
        TRIM(BALANCE.DECOSUBCODE07) AS "FULL WIDTH",
        USERGENERICGROUP_1.LONGDESCRIPTION,
        USERGENERICGROUP_2.LONGDESCRIPTION,
        USERGENERICGROUP_3.LONGDESCRIPTION,
        FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
        BALANCE.ELEMENTSCODE,                   -- set as text in excel
                        
        BALANCE.BASEPRIMARYQUANTITYUNIT,
        BALANCE.BASEPRIMARYUNITCODE,
        
        BALANCE.BASESECONDARYQUANTITYUNIT,
        BALANCE.BASESECONDARYUNITCODE,
        BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
        BALANCE.WAREHOUSELOCATIONCODE,
        BALANCE.QUALITYLEVELCODE,
        CASE BALANCE.STOCKTYPECODE
                WHEN '001' THEN 'Balance'
                WHEN '002' THEN 'Provisional Stock'
        END AS STOCKTYPE,
        BALANCE.LOTCODE,
        UPPER(SALESORDER.CREATIONUSER)  AS "CSALESORDER" ,
        TRIM(SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE) AS "CUSTOMERCODE",
        BUSINESSPARTNER.LEGALNAME1 
        
FROM DB2ADMIN.BALANCE BALANCE
        LEFT JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON 
                BALANCE.DECOSUBCODE01 = FULLITEMKEYDECODER.SUBCODE01
                AND BALANCE.DECOSUBCODE02 = FULLITEMKEYDECODER.SUBCODE02
                AND BALANCE.DECOSUBCODE03 = FULLITEMKEYDECODER.SUBCODE03
                AND BALANCE.DECOSUBCODE04 = FULLITEMKEYDECODER.SUBCODE04
                AND BALANCE.DECOSUBCODE05 = FULLITEMKEYDECODER.SUBCODE05
                AND BALANCE.DECOSUBCODE06 = FULLITEMKEYDECODER.SUBCODE06
                AND BALANCE.DECOSUBCODE07 = FULLITEMKEYDECODER.SUBCODE07
        LEFT JOIN DB2ADMIN.SALESORDER SALESORDER ON 
                LEFT(BALANCE.PROJECTCODE, 10) = SALESORDER.CODE
        LEFT JOIN DB2ADMIN.ORDERPARTNER ORDERPARTNER ON 
                SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
                -- DUPLICATE CUSTOMERSUPPLIERCODE
                AND ORDERPARTNER.CUSTOMERSUPPLIERTYPE = '1'
        LEFT JOIN DB2ADMIN.BUSINESSPARTNER BUSINESSPARTNER ON 
                ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
        LEFT JOIN DB2ADMIN.USERGENERICGROUP USERGENERICGROUP_1 ON 
                USERGENERICGROUP_1.CODE = BALANCE.DECOSUBCODE01
        LEFT JOIN DB2ADMIN.USERGENERICGROUP USERGENERICGROUP_2 ON 
                USERGENERICGROUP_2.CODE = BALANCE.DECOSUBCODE02    
        LEFT JOIN DB2ADMIN.USERGENERICGROUP USERGENERICGROUP_3 ON 
                USERGENERICGROUP_3.CODE = BALANCE.DECOSUBCODE04              
        
WHERE BALANCE.LOGICALWAREHOUSECODE IN ('DP10FFB1')
ORDER BY BALANCE.CREATIONDATETIME DESC;


--------------------------------------------------------------------------------------------



























